# If there is multiple container

# using docker-compose we can setup,create,destroy multiple containers

# here we write the configuration for all the containers

# version:'25.0.3'

version: "3.8"

services:
  postgres:
    image: postgres # hub.docker.com
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"